---
title: "ggplot_intro.rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Plan
We'll load libraries and learn ggplot2.

```{r Name you Rchunks}
summary(cars)
```

## Load libraries
```{r Library load}
    # loading libraries
    
    library(dplyr)
    library(gapminder)
    library(ggplot2) # install.packages('ggplot2')
    
    ## subset our data
    g <- gapminder %>% 
        filter(year == 2007) %>% 
        mutate(pop_m = pop/1e6)
    
    summary(g)

```

# My first plot

```{r}

## ggplot(data, aes(what's x, what's y) + what kind of plot)
s <- ggplot(g, aes(x = gdpPercap, y = lifeExp)) +
    geom_point()
s
```

# My second plot
a simple geom_point with aes()

```{r}
s2 <-  s + aes(size = pop_m)
s2

s3 <-  s2 + aes(color = continent)
s3

```

# nice piped!

```{r}

s <- ggplot(g, aes(x = gdpPercap, y = lifeExp)) +
    geom_point() + 
    aes(size = pop_m) + 
    aes(color = continent) +
    ggtitle('Health and Wealth of Nations for 2007') +
    xlab('GDP per capita (USD/year)') + 
    ylab('Life expectency (years)') +
    scale_colour_discrete('Continent') + 
    scale_size_continuous('Population (M)')
s

```

## Make a boxplot
This is my boxplot of continent and life expectency. Using 'g', which is a 
subset of 2007

```{r}

 
    b <- ggplot(g, aes(x = continent, y = lifeExp)) +
    geom_boxplot() + 
    aes(fill = continent) + 
    theme(legend.position = 'none')
    b

```

## GoogleVis interactive figure

```{r, results = 'asis'}

suppressPackageStartupMessages(library(googleVis))
 # install.packages('googleVis')

op <- options(gvis.plot.tag='chart')

m = gvisMotionChart(
  gapminder %>%
    mutate(
      pop_m = pop / 1e6,
      log_gdpPercap = log(gdpPercap)), 
  idvar='country', 
  timevar='year', 
  xvar='log_gdpPercap', 
  yvar='lifeExp', 
  colorvar='continent',
  sizevar='pop_m')
plot(m)


```